// Generated by CoffeeScript 1.6.1
var JSLog, getBounds, getBrowser, random, sprintf,
  __slice = [].slice;

JSLog = function() {
  var a, b, data, _i, _len;
  a = arguments[0], b = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  for (_i = 0, _len = b.length; _i < _len; _i++) {
    data = b[_i];
    a = a.replace('%@', data);
  }
  console.log(a);
  return a;
};

sprintf = function() {
  var a, b, data, data2, match, num, repstr, zero, _i, _len;
  a = arguments[0], b = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  for (_i = 0, _len = b.length; _i < _len; _i++) {
    data = b[_i];
    match = a.match(/%0\d*@/);
    if ((match != null)) {
      repstr = match[0];
      num = parseInt(repstr.match(/\d+/));
      zero = "";
      while (zero.length < num) {
        zero += "0";
      }
      data2 = (zero + data).substr(-num);
      a = a.replace(repstr, data2);
    } else {
      a = a.replace('%@', data);
    }
  }
  return a;
};

getBounds = function() {
  var frame, height, width;
  width = document.width;
  if (width == null) {
    width = document.documentElement.clientWidth - 1;
  }
  height = document.height;
  if (height == null) {
    height = document.documentElement.clientHeight - 1;
  }
  frame = [];
  frame.size = [];
  frame.size.width = width;
  frame.size.height = height;
  return frame;
};

random = function(max) {
  return Math.floor(Math.random() * (max + 1));
};

getBrowser = function() {
  var browser, kind, ua;
  ua = navigator.userAgent;
  if (ua.match(".*iPhone.*")) {
    kind = 'iOS';
  } else if (ua.match(".*Android")) {
    kind = 'Android';
  } else if (ua.match(".*Windows.*")) {
    kind = 'Windows';
  } else if (ua.match(".*BlackBerry.*")) {
    kind = 'BlackBerry';
  } else if (ua.match(".*Symbian.*")) {
    kind = 'Symbian';
  } else if (ua.match(".*Macintosh.*")) {
    kind = 'Mac';
  } else if (ua.match(".*Linux.*")) {
    kind = 'Linux';
  } else {
    kind = 'Unknown';
  }
  if (ua.match(".*Safari.*") && !ua.match(".*Android.*") && !ua.match(".*Chrome.*")) {
    browser = 'Safari';
  } else if (ua.match(".*Gecko.*Firefox.*")) {
    browser = "Firefox";
  } else if (ua.match(".*Opera*")) {
    browser = "Opera";
  } else if (ua.match(".*MSIE*")) {
    browser = "MSIE";
  } else if (ua.match(".*Gecko.*Chrome.*")) {
    browser = "Chrome";
  } else {
    browser = 'Unknown';
  }
  return {
    'kind': kind,
    'browser': browser
  };
};
