// Generated by CoffeeScript 1.6.1
var proc;

proc = function(gamepad) {
  var analog, axes, buttons, c, str, val, _i, _len, _ref, _ref1, _ref2, _ref3;
  gamepad.stat();
  str = "";
  _ref = gamepad.controllers;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    c = _ref[_i];
    if ((c != null)) {
      str += "<font style='font-weight:bold; font-size:24pt;'>" + c.id + "</font><br><font style='font-weight:bold; font-size:14pt;'>";
      _ref1 = c.buttons;
      for (buttons in _ref1) {
        val = _ref1[buttons];
        str += buttons + "=[" + val + "]<br>";
      }
      _ref2 = c.analog;
      for (analog in _ref2) {
        val = _ref2[analog];
        str += analog + "=[" + val + "]<br>";
      }
      _ref3 = c.axes;
      for (axes in _ref3) {
        val = _ref3[axes];
        str += axes + "=[" + val + "]<br>";
      }
      str += "</font><hr>";
    }
  }
  $("#main").html(str);
  return window.requestAnimationFrame(proc.bind(null, gamepad));
};

$(function() {
  var bounds, gamepad, height, width;
  bounds = getBounds();
  width = bounds.size.width;
  height = bounds.size.height;
  gamepad = new enforceGamepad();
  return proc(gamepad);
});
